#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Imath
Version  : v3.0.2
Release  : 2
URL      : https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.0.2.tar.gz
Source0  : https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.0.2.tar.gz
Summary  : Python bindings for the Imath libraries
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Imath-lib = %{version}-%{release}
Requires: Imath-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : python3
BuildRequires : python3-dev

%description
[![License](https://img.shields.io/github/license/AcademySoftwareFoundation/Imath)](LICENSE.md)
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/2799/badge)](https://bestpractices.coreinfrastructure.org/projects/2799)
[![Build Status](https://dev.azure.com/academysoftwarefoundation/Academy%20Software%20Foundation/_apis/build/status/academysoftwarefoundation.Imath)](https://dev.azure.com/academysoftwarefoundation/Academy%20Software%20Foundation/_build?definitionId=4&_a=summary)
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=AcademySoftwareFoundation_Imath&metric=alert_status)](https://sonarcloud.io/dashboard?id=AcademySoftwareFoundation_Imath)

%package dev
Summary: dev components for the Imath package.
Group: Development
Requires: Imath-lib = %{version}-%{release}
Provides: Imath-devel = %{version}-%{release}
Requires: Imath = %{version}-%{release}

%description dev
dev components for the Imath package.


%package lib
Summary: lib components for the Imath package.
Group: Libraries
Requires: Imath-license = %{version}-%{release}

%description lib
lib components for the Imath package.


%package license
Summary: license components for the Imath package.
Group: Default

%description license
license components for the Imath package.


%prep
%setup -q -n Imath-3.0.2
cd %{_builddir}/Imath-3.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1621357282
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=haswell "
export CFLAGS="$CFLAGS -march=haswell -m64"
export CXXFLAGS="$CXXFLAGS -march=haswell -m64"
export FFLAGS="$FFLAGS -march=haswell -m64"
export FCFLAGS="$FCFLAGS -march=haswell -m64"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -march=skylake-avx512 "
export CFLAGS="$CFLAGS -march=skylake-avx512 -m64 "
export CXXFLAGS="$CXXFLAGS -march=skylake-avx512 -m64 "
export FFLAGS="$FFLAGS -march=skylake-avx512 -m64 "
export FCFLAGS="$FCFLAGS -march=skylake-avx512 -m64 "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test
cd ../clr-build-avx2;
make test || :
cd ../clr-build-avx512;
make test || :

%install
export SOURCE_DATE_EPOCH=1621357282
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Imath
cp %{_builddir}/Imath-3.0.2/LICENSE.md %{buildroot}/usr/share/package-licenses/Imath/ce40fed41edcb2473538bb84f85ff79e585760b5
pushd clr-build-avx512
%make_install_avx512  || :
popd
pushd clr-build-avx2
%make_install_avx2  || :
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/Imath/ImathBox.h
/usr/include/Imath/ImathBoxAlgo.h
/usr/include/Imath/ImathColor.h
/usr/include/Imath/ImathColorAlgo.h
/usr/include/Imath/ImathConfig.h
/usr/include/Imath/ImathEuler.h
/usr/include/Imath/ImathExport.h
/usr/include/Imath/ImathForward.h
/usr/include/Imath/ImathFrame.h
/usr/include/Imath/ImathFrustum.h
/usr/include/Imath/ImathFrustumTest.h
/usr/include/Imath/ImathFun.h
/usr/include/Imath/ImathGL.h
/usr/include/Imath/ImathGLU.h
/usr/include/Imath/ImathInt64.h
/usr/include/Imath/ImathInterval.h
/usr/include/Imath/ImathLine.h
/usr/include/Imath/ImathLineAlgo.h
/usr/include/Imath/ImathMath.h
/usr/include/Imath/ImathMatrix.h
/usr/include/Imath/ImathMatrixAlgo.h
/usr/include/Imath/ImathNamespace.h
/usr/include/Imath/ImathPlane.h
/usr/include/Imath/ImathPlatform.h
/usr/include/Imath/ImathQuat.h
/usr/include/Imath/ImathRandom.h
/usr/include/Imath/ImathRoots.h
/usr/include/Imath/ImathShear.h
/usr/include/Imath/ImathSphere.h
/usr/include/Imath/ImathTypeTraits.h
/usr/include/Imath/ImathVec.h
/usr/include/Imath/ImathVecAlgo.h
/usr/include/Imath/half.h
/usr/include/Imath/halfFunction.h
/usr/include/Imath/halfLimits.h
/usr/lib64/cmake/Imath/ImathConfig.cmake
/usr/lib64/cmake/Imath/ImathConfigVersion.cmake
/usr/lib64/cmake/Imath/ImathTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Imath/ImathTargets.cmake
/usr/lib64/haswell/avx512_1/libImath-3_0.so
/usr/lib64/haswell/avx512_1/libImath.so
/usr/lib64/haswell/libImath-3_0.so
/usr/lib64/haswell/libImath.so
/usr/lib64/libImath-3_0.so
/usr/lib64/libImath.so
/usr/lib64/pkgconfig/Imath.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/avx512_1/libImath-3_0.so.28
/usr/lib64/haswell/avx512_1/libImath-3_0.so.28.0.0
/usr/lib64/haswell/libImath-3_0.so.28
/usr/lib64/haswell/libImath-3_0.so.28.0.0
/usr/lib64/libImath-3_0.so.28
/usr/lib64/libImath-3_0.so.28.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Imath/ce40fed41edcb2473538bb84f85ff79e585760b5
